-- ============================================================================
-- E-Library demo catalogue: 100 books spanning ~40 subject areas.
--
-- Broad topical coverage is the point: semantic search can only match what is
-- in the catalogue, so a wide spread means most reasonable searches land on
-- something relevant. Descriptions and tags are deliberately keyword-rich
-- because those fields are what actually get embedded (see
-- RecommendationService.initialize_vector_store).
--
-- Safe to re-run: ISBN is UNIQUE, so ON DUPLICATE KEY UPDATE refreshes rows
-- instead of duplicating them.
--
-- created_at / updated_at / available_copies / is_active / rating are set
-- explicitly and must stay that way — the Book response schema requires them,
-- and NULLs there make GET /api/v1/books/ fail with a 500.
--
-- ISBNs are illustrative demo values, not verified catalogue numbers.
--
-- RUN IT
--   Windows:  mysql -u root -p elibrary_db < seed_books.sql
--   macOS:    mysql -u root elibrary_db < seed_books.sql
--   phpMyAdmin / XAMPP: select elibrary_db, Import tab, choose this file.
--
-- AFTERWARDS: restart the backend. The vector store is built once per process
-- and cached, so a running server will not see these rows until it restarts.
-- ============================================================================

USE elibrary_db;

INSERT INTO books
    (isbn, title, author, publisher, publication_year, category, description,
     total_copies, available_copies, is_active, language, pages, rating, tags,
     created_at, updated_at)
VALUES
-- Artificial Intelligence ----------------------------------------------------
('978-0134610001','Artificial Intelligence: A Modern Approach','Stuart Russell, Peter Norvig','Pearson',2020,'Artificial Intelligence','The standard textbook on artificial intelligence, covering intelligent agents, search algorithms, knowledge representation, probabilistic reasoning, machine learning and robotics.',4,4,1,'English',1136,4.7,'ai,machine learning,agents,search,reasoning,robotics',NOW(),NOW()),
('978-0262035002','Deep Learning','Ian Goodfellow, Yoshua Bengio, Aaron Courville','MIT Press',2016,'Artificial Intelligence','A thorough introduction to deep neural networks: backpropagation, convolutional networks, recurrent networks, regularization, optimization and generative models.',3,3,1,'English',800,4.6,'deep learning,neural networks,cnn,rnn,gan',NOW(),NOW()),
('978-1492032003','Hands-On Machine Learning with Scikit-Learn and TensorFlow','Aurelien Geron','O''Reilly Media',2019,'Artificial Intelligence','A practical guide to building machine learning systems, from regression and decision trees through to deep neural networks trained with TensorFlow and Keras.',5,5,1,'English',856,4.8,'machine learning,python,tensorflow,keras,scikit-learn',NOW(),NOW()),
('978-1098136004','Natural Language Processing with Transformers','Lewis Tunstall, Leandro von Werra','O''Reilly Media',2022,'Artificial Intelligence','How transformer models work and how to apply them to text classification, named entity recognition, summarization, question answering and semantic search with embeddings.',3,3,1,'English',406,4.5,'nlp,transformers,embeddings,semantic search,language models',NOW(),NOW()),
('978-0136042005','Computer Vision: Algorithms and Applications','Richard Szeliski','Springer',2021,'Artificial Intelligence','Techniques for making computers interpret images and video: feature detection, image segmentation, object recognition, stereo vision and motion tracking.',2,2,1,'English',925,4.3,'computer vision,image processing,object detection,opencv',NOW(),NOW()),
('978-0262039006','Reinforcement Learning: An Introduction','Richard Sutton, Andrew Barto','MIT Press',2018,'Artificial Intelligence','How agents learn to make decisions through trial and error: Markov decision processes, dynamic programming, temporal difference learning and policy gradient methods.',2,2,1,'English',552,4.5,'reinforcement learning,agents,decision making,q-learning',NOW(),NOW()),

-- Programming ----------------------------------------------------------------
('978-0132350007','Clean Code: A Handbook of Agile Software Craftsmanship','Robert C. Martin','Prentice Hall',2008,'Programming','Principles and practices for writing readable, maintainable software: meaningful naming, small functions, error handling, unit testing and refactoring toward clarity.',4,4,1,'English',464,4.6,'clean code,refactoring,software craftsmanship,best practices',NOW(),NOW()),
('978-0201616008','The Pragmatic Programmer','Andrew Hunt, David Thomas','Addison-Wesley',2019,'Programming','A career-spanning guide to effective software development: avoiding duplication, designing for change, debugging methodically and automating repetitive work.',3,3,1,'English',352,4.7,'software engineering,best practices,debugging,career',NOW(),NOW()),
('978-1593279009','Python Crash Course','Eric Matthes','No Starch Press',2023,'Programming','A hands-on introduction to programming in Python, covering the basics of the language and building projects including games, data visualizations and web applications.',5,5,1,'English',552,4.6,'python,beginner,programming,projects',NOW(),NOW()),
('978-0596007010','Head First Design Patterns','Eric Freeman, Elisabeth Robson','O''Reilly Media',2021,'Programming','An accessible tour of object oriented design patterns: strategy, observer, decorator, factory, singleton and how to apply them to real software problems.',3,3,1,'English',694,4.4,'design patterns,object oriented,java,architecture',NOW(),NOW()),
('978-0262033011','Introduction to Algorithms','Thomas Cormen, Charles Leiserson','MIT Press',2022,'Programming','A comprehensive reference on algorithms and data structures: sorting, searching, graphs, dynamic programming, greedy methods and computational complexity.',4,4,1,'English',1312,4.5,'algorithms,data structures,complexity,sorting,graphs',NOW(),NOW()),

-- Web Development ------------------------------------------------------------
('978-1491954012','Learning React','Alex Banks, Eve Porcello','O''Reilly Media',2020,'Web Development','Building modern user interfaces with React: components, hooks, state management, routing and fetching data in single page applications.',4,4,1,'English',310,4.4,'react,javascript,frontend,hooks,components,ui',NOW(),NOW()),
('978-1801076013','Building Python Web APIs with FastAPI','Abdulazeez Abdulazeez Adeshina','Packt Publishing',2022,'Web Development','Designing and deploying REST APIs in Python with FastAPI: routing, dependency injection, request validation with Pydantic, authentication and automated testing.',3,3,1,'English',158,4.3,'fastapi,python,rest api,backend,pydantic',NOW(),NOW()),
('978-1593279014','Eloquent JavaScript','Marijn Haverbeke','No Starch Press',2018,'Web Development','A modern introduction to programming in JavaScript, covering the language, the browser document object model, and building interactive websites and web applications.',4,4,1,'English',472,4.2,'javascript,web,browser,dom,frontend',NOW(),NOW()),
('978-1119998015','HTML and CSS: Design and Build Websites','Jon Duckett','Wiley',2011,'Web Development','A visual beginner guide to creating web pages: HTML structure, CSS styling, layout, typography, forms and making a website look good on any screen.',5,5,1,'English',514,4.5,'html,css,web design,beginner,website,layout',NOW(),NOW()),
('978-1801812016','Full-Stack Web Development with Django','William Vincent','Packt Publishing',2022,'Web Development','Building complete web applications in Python with Django: models, views, templates, user accounts, deployment and connecting a database to a website.',3,3,1,'English',400,4.2,'django,python,full stack,web application,backend',NOW(),NOW()),
('978-1492052017','Node.js Design Patterns','Mario Casciaro','Packt Publishing',2020,'Web Development','Server side JavaScript at scale: asynchronous control flow, streams, module design, scalability patterns and building production Node applications.',2,2,1,'English',664,4.3,'nodejs,javascript,backend,async,server',NOW(),NOW()),

-- Databases ------------------------------------------------------------------
('978-1449373018','Designing Data-Intensive Applications','Martin Kleppmann','O''Reilly Media',2017,'Databases','The principles behind reliable, scalable and maintainable data systems: replication, partitioning, transactions, consistency, consensus and stream processing.',4,4,1,'English',616,4.9,'databases,distributed systems,scalability,replication,transactions',NOW(),NOW()),
('978-0321884019','SQL Antipatterns','Bill Karwin','Pragmatic Bookshelf',2010,'Databases','Common mistakes in database design and SQL queries and how to avoid them: poor normalization, bad indexing choices and unsafe query construction.',3,3,1,'English',328,4.5,'sql,database design,indexing,normalization,antipatterns',NOW(),NOW()),
('978-0596009020','MySQL Cookbook','Paul DuBois','O''Reilly Media',2014,'Databases','Practical recipes for working with MySQL: writing queries, designing schemas, indexing for performance, handling transactions and administering database servers.',3,3,1,'English',866,4.1,'mysql,sql,database administration,queries,performance',NOW(),NOW()),
('978-1617294021','MongoDB in Action','Kyle Banker','Manning Publications',2016,'Databases','Working with document databases: schema design without tables, queries and aggregation, indexing, replication and scaling MongoDB horizontally.',2,2,1,'English',480,4.0,'mongodb,nosql,document database,aggregation',NOW(),NOW()),

-- Cybersecurity --------------------------------------------------------------
('978-1118026022','The Web Application Hacker''s Handbook','Dafydd Stuttard, Marcus Pinto','Wiley',2011,'Cybersecurity','Finding and exploiting security flaws in web applications: authentication bypass, session hijacking, SQL injection, cross site scripting and broken access control.',3,3,1,'English',912,4.6,'security,web security,penetration testing,sql injection,xss,hacking',NOW(),NOW()),
('978-1593278023','Serious Cryptography','Jean-Philippe Aumasson','No Starch Press',2017,'Cybersecurity','How cryptography works in practice: hash functions, block ciphers, authenticated encryption, key exchange, digital signatures and transport layer security.',2,2,1,'English',304,4.4,'cryptography,encryption,security,tls,hashing,keys',NOW(),NOW()),
('978-1119643024','Network Security Essentials','William Stallings','Pearson',2020,'Cybersecurity','Protecting networks from attack: firewalls, intrusion detection, virtual private networks, wireless security and secure network protocol design.',3,3,1,'English',464,4.1,'network security,firewall,intrusion detection,vpn',NOW(),NOW()),
('978-1098128025','Practical Malware Analysis','Michael Sikorski, Andrew Honig','No Starch Press',2012,'Cybersecurity','Dissecting malicious software safely: static and dynamic analysis, disassembly, debugging, unpacking and recognising common malware behaviours.',2,2,1,'English',800,4.5,'malware,reverse engineering,forensics,security analysis',NOW(),NOW()),

-- Networking and Systems -----------------------------------------------------
('978-0136081026','Computer Networking: A Top-Down Approach','James Kurose, Keith Ross','Pearson',2021,'Networking','How the internet works, layer by layer: HTTP and the web, transport protocols, routing, link layer technologies and wireless networks.',4,4,1,'English',864,4.4,'networking,internet,tcp ip,http,routing,protocols',NOW(),NOW()),
('978-1492052027','TCP/IP Illustrated','W. Richard Stevens','Addison-Wesley',2011,'Networking','A detailed examination of the protocols that carry internet traffic, tracing real packets through TCP, UDP, IP, DNS and related services.',2,2,1,'English',1056,4.5,'tcp ip,protocols,packets,dns,networking',NOW(),NOW()),
('978-0134092028','Operating System Concepts','Abraham Silberschatz','Wiley',2018,'Operating Systems','The fundamentals of operating systems: processes and threads, CPU scheduling, memory management, virtual memory, file systems and deadlock handling.',4,4,1,'English',1040,4.2,'operating systems,processes,memory management,scheduling,file systems',NOW(),NOW()),
('978-1593279029','How Linux Works','Brian Ward','No Starch Press',2021,'Operating Systems','What happens under the hood of a Linux system: the boot process, devices, file systems, networking configuration, shell scripting and system maintenance.',3,3,1,'English',464,4.3,'linux,unix,shell,system administration,command line',NOW(),NOW()),
('978-1492082030','Kubernetes Up and Running','Brendan Burns, Joe Beda','O''Reilly Media',2022,'Cloud Computing','Deploying and operating containerized applications with Kubernetes: pods, services, deployments, config management, storage and cluster scaling.',3,3,1,'English',278,4.2,'kubernetes,containers,docker,cloud,devops,orchestration',NOW(),NOW()),
('978-1492083031','Docker Deep Dive','Nigel Poulton','Independently Published',2023,'Cloud Computing','Containers explained from first principles: images, registries, networking, volumes, orchestration with Swarm and building production container workflows.',3,3,1,'English',350,4.4,'docker,containers,devops,cloud,deployment',NOW(),NOW()),
('978-1492046032','Site Reliability Engineering','Betsy Beyer, Chris Jones','O''Reilly Media',2016,'Cloud Computing','How Google runs production systems: service level objectives, monitoring, incident response, postmortems, release engineering and eliminating toil.',2,2,1,'English',552,4.3,'sre,devops,monitoring,reliability,incident response',NOW(),NOW()),

-- Mobile Development ---------------------------------------------------------
('978-1617296033','Flutter in Action','Eric Windmill','Manning Publications',2020,'Mobile Development','Building cross platform mobile apps for Android and iOS from a single Dart codebase: widgets, layout, state management, animation and platform channels.',3,3,1,'English',368,4.2,'flutter,dart,mobile app,android,ios,cross platform',NOW(),NOW()),
('978-1491954034','Android Programming: The Big Nerd Ranch Guide','Bill Phillips, Chris Stewart','Big Nerd Ranch',2022,'Mobile Development','Writing Android applications in Kotlin: activities and fragments, layouts, data persistence, background work and publishing to the Play Store.',3,3,1,'English',720,4.3,'android,kotlin,mobile app,ui,play store',NOW(),NOW()),
('978-1801812035','React Native Cookbook','Dan Ward','Packt Publishing',2019,'Mobile Development','Recipes for building mobile applications with React Native: navigation, native modules, animations, offline storage and performance tuning.',2,2,1,'English',442,4.0,'react native,javascript,mobile app,ios,android',NOW(),NOW()),

-- Data Science and Statistics ------------------------------------------------
('978-1491957036','Python for Data Analysis','Wes McKinney','O''Reilly Media',2022,'Data Science','Manipulating, cleaning and analysing data in Python with pandas and NumPy: loading datasets, reshaping, grouping, time series and plotting results.',4,4,1,'English',579,4.5,'data analysis,python,pandas,numpy,data cleaning',NOW(),NOW()),
('978-1492041037','Storytelling with Data','Cole Nussbaumer Knaflic','Wiley',2015,'Data Science','Turning numbers into clear visual communication: choosing the right chart, removing clutter, directing attention and building a narrative around data.',3,3,1,'English',288,4.6,'data visualization,charts,communication,dashboards',NOW(),NOW()),
('978-0387848038','The Elements of Statistical Learning','Trevor Hastie, Robert Tibshirani','Springer',2017,'Data Science','The mathematical foundations of statistical learning: linear methods, kernel smoothing, model selection, tree based methods, boosting and unsupervised learning.',2,2,1,'English',745,4.4,'statistics,statistical learning,regression,classification,modelling',NOW(),NOW()),
('978-1119584039','Practical Statistics for Data Scientists','Peter Bruce, Andrew Bruce','O''Reilly Media',2020,'Data Science','The statistical concepts that matter most in data work: sampling and bias, significance testing, regression, classification and resampling methods.',3,3,1,'English',368,4.3,'statistics,data science,hypothesis testing,regression,sampling',NOW(),NOW()),

-- Mathematics ----------------------------------------------------------------
('978-0134689040','Linear Algebra and Its Applications','David Lay','Pearson',2020,'Mathematics','Vectors, matrices and linear transformations, with applications to computer graphics, engineering systems, least squares fitting and machine learning.',4,4,1,'English',576,4.2,'linear algebra,matrices,vectors,eigenvalues,mathematics',NOW(),NOW()),
('978-1285741041','Calculus: Early Transcendentals','James Stewart','Cengage Learning',2020,'Mathematics','A standard course in differential and integral calculus: limits, derivatives, integration techniques, sequences and series, and multivariable calculus.',5,5,1,'English',1368,4.1,'calculus,derivatives,integration,limits,mathematics',NOW(),NOW()),
('978-0073383042','Discrete Mathematics and Its Applications','Kenneth Rosen','McGraw-Hill',2019,'Mathematics','The mathematics behind computer science: logic and proof, set theory, combinatorics, graph theory, recursion and number theory.',4,4,1,'English',1120,4.0,'discrete mathematics,logic,graph theory,combinatorics,proofs',NOW(),NOW()),
('978-0134757043','Probability and Statistics for Engineers','Ronald Walpole','Pearson',2016,'Mathematics','Probability distributions, sampling, estimation and hypothesis testing, with worked engineering and scientific applications throughout.',3,3,1,'English',816,4.0,'probability,statistics,distributions,engineering,estimation',NOW(),NOW()),

-- Physical Sciences ----------------------------------------------------------
('978-1119539044','Fundamentals of Physics','David Halliday, Robert Resnick','Wiley',2021,'Physics','A calculus based introduction to physics: mechanics, thermodynamics, waves, electricity and magnetism, optics and modern physics.',4,4,1,'English',1450,4.3,'physics,mechanics,thermodynamics,electricity,magnetism,optics',NOW(),NOW()),
('978-0131118045','Introduction to Quantum Mechanics','David Griffiths','Cambridge University Press',2018,'Physics','The formalism and applications of quantum theory: the Schrodinger equation, wave functions, angular momentum, spin and perturbation methods.',2,2,1,'English',508,4.4,'quantum mechanics,physics,wave function,schrodinger',NOW(),NOW()),
('978-0393609046','Astrophysics for People in a Hurry','Neil deGrasse Tyson','W. W. Norton',2017,'Physics','A short accessible tour of the universe: the big bang, dark matter and dark energy, galaxies, exoplanets and our place in the cosmos.',3,3,1,'English',224,4.5,'astronomy,astrophysics,universe,cosmology,space',NOW(),NOW()),
('978-1305957047','Chemistry: The Central Science','Theodore Brown, Eugene LeMay','Pearson',2021,'Chemistry','General chemistry from atomic structure through bonding, stoichiometry, thermochemistry, equilibrium, acids and bases and electrochemistry.',4,4,1,'English',1248,4.1,'chemistry,atoms,bonding,reactions,equilibrium',NOW(),NOW()),
('978-1119316048','Organic Chemistry','Paula Bruice','Pearson',2020,'Chemistry','The structure and reactivity of carbon compounds: functional groups, reaction mechanisms, stereochemistry, spectroscopy and synthesis strategies.',3,3,1,'English',1344,4.0,'organic chemistry,reactions,mechanisms,synthesis,molecules',NOW(),NOW()),
('978-0716743049','Principles of Biochemistry','David Nelson, Michael Cox','W. H. Freeman',2021,'Chemistry','The chemistry of living systems: proteins and enzymes, carbohydrates, lipids, metabolism, and the storage and expression of genetic information.',3,3,1,'English',1328,4.3,'biochemistry,proteins,enzymes,metabolism,molecular biology',NOW(),NOW()),

-- Life Sciences and Medicine -------------------------------------------------
('978-0815345050','Molecular Biology of the Cell','Bruce Alberts','W. W. Norton',2022,'Biology','How cells work at the molecular level: DNA replication and repair, gene expression, membranes, signalling, the cytoskeleton and cell division.',3,3,1,'English',1464,4.5,'cell biology,molecular biology,dna,genetics,proteins',NOW(),NOW()),
('978-0321775051','Campbell Biology','Lisa Urry, Michael Cain','Pearson',2020,'Biology','A broad survey of the life sciences: evolution, genetics, cell structure, plant and animal physiology, ecology and biodiversity.',4,4,1,'English',1488,4.3,'biology,evolution,genetics,ecology,physiology',NOW(),NOW()),
('978-1259644052','Microbiology: An Introduction','Gerard Tortora','Pearson',2019,'Biology','The world of microorganisms: bacterial structure and growth, viruses, immunology, infectious disease and the control of microbial populations.',3,3,1,'English',960,4.1,'microbiology,bacteria,viruses,infection,immunology',NOW(),NOW()),
('978-1259644053','Harrison''s Principles of Internal Medicine','Joseph Loscalzo','McGraw-Hill',2022,'Medicine','A clinical reference covering the diagnosis and management of disease across cardiology, respiratory medicine, endocrinology, oncology and infectious disease.',2,2,1,'English',4000,4.6,'medicine,clinical,diagnosis,disease,internal medicine',NOW(),NOW()),
('978-0323673054','Gray''s Anatomy for Students','Richard Drake','Elsevier',2019,'Medicine','Human anatomy organised by body region, linking structure to clinical practice with imaging and surface anatomy throughout.',3,3,1,'English',1160,4.4,'anatomy,human body,medicine,physiology,clinical',NOW(),NOW()),
('978-0323401055','Essentials of Nursing Practice','Patricia Potter','Elsevier',2021,'Medicine','Core nursing skills and concepts: patient assessment, infection control, medication administration, wound care and the ethics of patient centred care.',3,3,1,'English',1400,4.2,'nursing,patient care,clinical skills,healthcare',NOW(),NOW()),
('978-1975118056','Public Health: Principles and Practice','Mary-Jane Schneider','Jones and Bartlett',2020,'Medicine','How population health is protected: epidemiology, disease surveillance, health promotion, environmental health and health policy.',2,2,1,'English',672,4.0,'public health,epidemiology,disease prevention,health policy',NOW(),NOW()),

-- Social Sciences ------------------------------------------------------------
('978-0374533057','Thinking, Fast and Slow','Daniel Kahneman','Farrar, Straus and Giroux',2013,'Psychology','How two systems of thought drive human judgement: fast intuitive reasoning and slow deliberate analysis, and the cognitive biases that follow.',4,4,1,'English',499,4.4,'psychology,decision making,cognitive bias,behavioural economics',NOW(),NOW()),
('978-1319050058','Psychology','David Myers, Nathan DeWall','Worth Publishers',2021,'Psychology','An introduction to the science of mind and behaviour: perception, memory, learning, development, personality, disorders and social psychology.',4,4,1,'English',768,4.2,'psychology,behaviour,memory,learning,mental health',NOW(),NOW()),
('978-0525559059','Atomic Habits','James Clear','Avery',2018,'Self-Help','A practical framework for building good habits and breaking bad ones through small consistent changes, habit stacking and environment design.',5,5,1,'English',320,4.7,'habits,productivity,self improvement,behaviour change,motivation',NOW(),NOW()),
('978-1847941060','Deep Work','Cal Newport','Grand Central Publishing',2016,'Self-Help','Why the ability to focus without distraction is becoming rare and valuable, and how to train it in a world of constant interruption.',3,3,1,'English',304,4.5,'focus,productivity,concentration,work,distraction',NOW(),NOW()),
('978-0143127061','Sapiens: A Brief History of Humankind','Yuval Noah Harari','Harper',2015,'History','How Homo sapiens came to dominate the planet, tracing the cognitive, agricultural and scientific revolutions and their effect on human society.',4,4,1,'English',464,4.6,'history,anthropology,civilization,human evolution,society',NOW(),NOW()),
('978-0141034062','A History of Nigeria','Toyin Falola, Matthew Heaton','Cambridge University Press',2008,'History','Nigeria from its precolonial kingdoms through British colonial rule, independence, civil war and the challenges of the modern federal republic.',3,3,1,'English',360,4.3,'nigeria,african history,colonialism,independence,politics',NOW(),NOW()),
('978-0140449063','The Republic','Plato','Penguin Classics',2007,'Philosophy','Plato''s dialogue on justice, the ideal state, the theory of forms and the education of rulers, including the allegory of the cave.',3,3,1,'English',416,4.2,'philosophy,ethics,justice,politics,classics',NOW(),NOW()),
('978-0192854064','A Very Short Introduction to Philosophy','Edward Craig','Oxford University Press',2002,'Philosophy','A brief tour of the central questions of philosophy: knowledge, mind and body, free will, morality and the existence of God.',2,2,1,'English',144,4.0,'philosophy,ethics,logic,knowledge,introduction',NOW(),NOW()),
('978-0393355065','Why Nations Fail','Daron Acemoglu, James Robinson','Crown Business',2013,'Economics','Why some countries become prosperous and others stay poor, arguing that inclusive political and economic institutions are the decisive factor.',3,3,1,'English',544,4.4,'economics,development,institutions,poverty,politics',NOW(),NOW()),
('978-0134078066','Principles of Economics','N. Gregory Mankiw','Cengage Learning',2020,'Economics','An introduction to how economies work: supply and demand, market structures, macroeconomic aggregates, monetary policy and international trade.',4,4,1,'English',880,4.1,'economics,microeconomics,macroeconomics,markets,trade',NOW(),NOW()),
('978-0198776067','Development Economics','Debraj Ray','Princeton University Press',2018,'Economics','The economics of poor countries: poverty and inequality, population growth, agriculture, credit markets, trade policy and the path to development.',2,2,1,'English',848,4.2,'development economics,poverty,inequality,growth,policy',NOW(),NOW()),
('978-1509849068','Political Science: An Introduction','Michael Roskin','Pearson',2021,'Political Science','The study of power and government: political ideologies, constitutions, elections, parties, public opinion and international relations.',3,3,1,'English',480,4.0,'political science,government,democracy,elections,ideology',NOW(),NOW()),
('978-0198784069','International Relations Theory','Tim Dunne, Milja Kurki','Oxford University Press',2020,'Political Science','The competing frameworks used to explain world politics: realism, liberalism, constructivism, Marxism and postcolonial approaches.',2,2,1,'English',400,4.1,'international relations,diplomacy,foreign policy,global politics',NOW(),NOW()),

-- Law -------------------------------------------------------------------------
('978-0198853070','Constitutional and Administrative Law','Neil Parpworth','Oxford University Press',2022,'Law','The legal structure of the state: separation of powers, parliamentary sovereignty, judicial review, human rights and the limits of executive action.',3,3,1,'English',528,4.1,'law,constitutional law,human rights,judicial review,government',NOW(),NOW()),
('978-1292251071','Contract Law','Ewan McKendrick','Pearson',2021,'Law','The formation, interpretation and enforcement of agreements: offer and acceptance, consideration, terms, breach, remedies and unfair contract terms.',3,3,1,'English',736,4.2,'law,contract law,agreements,breach,remedies',NOW(),NOW()),
('978-1526518072','Criminal Law','Jonathan Herring','Oxford University Press',2022,'Law','Offences and defences in criminal law: intention and recklessness, homicide, theft and fraud, sexual offences and the principles of criminal liability.',3,3,1,'English',912,4.2,'law,criminal law,offences,liability,justice',NOW(),NOW()),

-- Business, Finance and Management --------------------------------------------
('978-0307887073','The Lean Startup','Eric Ries','Crown Business',2011,'Business','Building startups through validated learning, rapid experimentation with minimum viable products, and knowing when to pivot or persevere.',4,4,1,'English',336,4.2,'startup,entrepreneurship,innovation,product management,business',NOW(),NOW()),
('978-0062316074','Good to Great','Jim Collins','HarperBusiness',2001,'Business','What separates companies that make a lasting leap in performance from those that do not, based on a long study of comparable firms.',3,3,1,'English',320,4.3,'business,leadership,management,strategy,performance',NOW(),NOW()),
('978-1591847075','Zero to One','Peter Thiel','Crown Business',2014,'Business','Notes on building companies that create genuinely new things rather than copying what already works, and the role of monopoly and secrets in startups.',3,3,1,'English',224,4.2,'startup,entrepreneurship,innovation,venture capital,strategy',NOW(),NOW()),
('978-1119491076','Project Management: A Systems Approach','Harold Kerzner','Wiley',2022,'Business','Planning, scheduling and controlling projects: work breakdown structures, critical path analysis, risk management, budgeting and stakeholder communication.',3,3,1,'English',848,4.1,'project management,planning,scheduling,risk,pmp',NOW(),NOW()),
('978-1292295077','Financial Accounting','Walter Harrison, Charles Horngren','Pearson',2021,'Accounting','Recording and reporting financial transactions: the accounting equation, journals and ledgers, adjusting entries, and preparing financial statements.',4,4,1,'English',816,4.0,'accounting,financial statements,bookkeeping,balance sheet,ledger',NOW(),NOW()),
('978-1119595078','Corporate Finance','Stephen Ross, Randolph Westerfield','McGraw-Hill',2021,'Accounting','How firms raise and allocate capital: time value of money, valuation, capital budgeting, cost of capital, dividend policy and risk management.',3,3,1,'English',1024,4.1,'finance,valuation,capital budgeting,investment,risk',NOW(),NOW()),
('978-0132479079','Auditing and Assurance Services','Alvin Arens','Pearson',2020,'Accounting','The audit process from planning to reporting: internal control evaluation, evidence gathering, sampling, fraud detection and professional ethics.',2,2,1,'English',880,4.0,'auditing,assurance,internal control,fraud,ethics',NOW(),NOW()),
('978-0134292080','Marketing Management','Philip Kotler, Kevin Keller','Pearson',2021,'Marketing','Building and delivering customer value: market segmentation, positioning, branding, pricing, distribution channels and integrated communications.',3,3,1,'English',832,4.2,'marketing,branding,strategy,customers,advertising',NOW(),NOW()),
('978-1119617081','Digital Marketing Strategy','Simon Kingsnorth','Kogan Page',2022,'Marketing','Planning marketing in online channels: search engine optimisation, content marketing, social media, email campaigns, analytics and attribution.',3,3,1,'English',424,4.1,'digital marketing,seo,social media,content,analytics',NOW(),NOW()),

-- Engineering and Built Environment --------------------------------------------
('978-0134610082','Structural Analysis','Russell Hibbeler','Pearson',2020,'Civil Engineering','Analysing the forces in beams, trusses, frames and cables, including influence lines, deflections and statically indeterminate structures.',3,3,1,'English',720,4.1,'civil engineering,structures,beams,trusses,statics',NOW(),NOW()),
('978-0071086083','Reinforced Concrete Design','Jack McCormac','Wiley',2019,'Civil Engineering','Designing concrete structures to code: beams and slabs in flexure and shear, columns, footings, retaining walls and serviceability requirements.',2,2,1,'English',744,4.0,'concrete,structural design,construction,civil engineering,buildings',NOW(),NOW()),
('978-1259822084','Fluid Mechanics','Frank White','McGraw-Hill',2021,'Mechanical Engineering','The behaviour of liquids and gases in motion: pressure and viscosity, control volume analysis, pipe flow, boundary layers and turbomachinery.',3,3,1,'English',864,4.1,'fluid mechanics,hydraulics,flow,pressure,mechanical engineering',NOW(),NOW()),
('978-1119175085','Thermodynamics: An Engineering Approach','Yunus Cengel','McGraw-Hill',2020,'Mechanical Engineering','Energy, heat and work in engineering systems: the laws of thermodynamics, power and refrigeration cycles, and combustion processes.',3,3,1,'English',1024,4.2,'thermodynamics,heat transfer,energy,engines,mechanical engineering',NOW(),NOW()),
('978-0133760086','Electric Circuits','James Nilsson, Susan Riedel','Pearson',2021,'Electrical Engineering','Analysing circuits from first principles: resistive networks, operational amplifiers, transient response, sinusoidal steady state and frequency response.',4,4,1,'English',816,4.1,'circuits,electronics,voltage,current,electrical engineering',NOW(),NOW()),
('978-0134520087','Digital Design and Computer Architecture','David Harris, Sarah Harris','Morgan Kaufmann',2022,'Electrical Engineering','From logic gates to working processors: boolean algebra, sequential circuits, hardware description languages, microarchitecture and memory systems.',3,3,1,'English',624,4.4,'digital design,logic gates,processor,verilog,computer architecture',NOW(),NOW()),
('978-1119456088','Power System Analysis','John Grainger, William Stevenson','McGraw-Hill',2019,'Electrical Engineering','Modelling and operating electrical power networks: transmission line parameters, load flow, fault analysis, stability and economic dispatch.',2,2,1,'English',800,4.0,'power systems,electricity,transmission,grid,energy',NOW(),NOW()),
('978-1119540089','Renewable Energy Engineering','Nicholas Jenkins, Janaka Ekanayake','Cambridge University Press',2017,'Environmental Science','The engineering behind clean energy: solar photovoltaics, wind turbines, hydropower, bioenergy and integrating renewables into the electricity grid.',3,3,1,'English',432,4.2,'renewable energy,solar,wind,sustainability,climate',NOW(),NOW()),
('978-0134605090','Environmental Science: A Global Concern','William Cunningham','McGraw-Hill',2021,'Environmental Science','Human impact on natural systems: biodiversity loss, water and air pollution, climate change, waste management and sustainable resource use.',3,3,1,'English',640,4.1,'environment,climate change,pollution,sustainability,conservation',NOW(),NOW()),
('978-1856178091','Architecture: Form, Space and Order','Francis Ching','Wiley',2015,'Architecture','The vocabulary of architectural design: point, line, plane and volume, proportion and scale, circulation, and the organisation of space.',3,3,1,'English',464,4.5,'architecture,design,space,buildings,drawing',NOW(),NOW()),
('978-0470641092','Building Construction Illustrated','Francis Ching','Wiley',2020,'Architecture','How buildings are put together: foundations, structural systems, envelopes, roofing, finishes and the coordination of building services.',2,2,1,'English',480,4.4,'construction,buildings,architecture,materials,structures',NOW(),NOW()),

-- Agriculture ------------------------------------------------------------------
('978-0851994093','Principles of Crop Production','George Acquaah','Pearson',2018,'Agriculture','Growing field crops successfully: soil preparation, planting, nutrient and water management, pest control and harvest practices.',3,3,1,'English',736,4.0,'agriculture,crops,farming,soil,irrigation',NOW(),NOW()),
('978-0813821094','Animal Science and Livestock Production','Bruce Taylor','Wiley',2019,'Agriculture','Raising healthy livestock: animal nutrition, breeding and genetics, housing, disease prevention and the economics of livestock enterprises.',2,2,1,'English',560,4.0,'livestock,animal science,poultry,cattle,farming',NOW(),NOW()),
('978-0128119095','Soil Science and Management','Edward Plaster','Cengage Learning',2020,'Agriculture','Understanding soil as a growing medium: texture and structure, fertility, pH management, erosion control and sustainable land practices.',2,2,1,'English',528,4.1,'soil science,fertility,erosion,land management,agriculture',NOW(),NOW()),

-- Education ---------------------------------------------------------------------
('978-0134995096','Educational Psychology','Anita Woolfolk','Pearson',2021,'Education','How students learn and how teaching can support it: cognitive development, motivation, classroom management, assessment and individual differences.',3,3,1,'English',624,4.1,'education,teaching,learning,classroom,assessment',NOW(),NOW()),
('978-0807758097','Pedagogy of the Oppressed','Paulo Freire','Bloomsbury Academic',2018,'Education','A critique of banking style education and an argument for dialogue based teaching that develops critical consciousness in learners.',2,2,1,'English',192,4.4,'education,pedagogy,critical thinking,teaching,philosophy',NOW(),NOW()),
('978-1416625098','Curriculum Development and Instructional Design','Jon Wiles','Pearson',2019,'Education','Planning what gets taught and how: needs analysis, learning objectives, curriculum mapping, instructional strategies and programme evaluation.',2,2,1,'English',368,4.0,'curriculum,instructional design,teaching,school,planning',NOW(),NOW()),

-- Literature ---------------------------------------------------------------------
('978-0385474099','Things Fall Apart','Chinua Achebe','Anchor Books',1994,'African Literature','The story of Okonkwo, a leader in a nineteenth century Igbo village in Nigeria, and the disruption of his community by British colonialism and missionaries.',5,5,1,'English',209,4.5,'nigerian literature,igbo,colonialism,classic,novel,fiction',NOW(),NOW()),
('978-1400096100','Half of a Yellow Sun','Chimamanda Ngozi Adichie','Anchor Books',2007,'African Literature','Set during the Nigerian Civil War, the intertwined lives of a professor, a houseboy and twin sisters as Biafra fights for independence.',4,4,1,'English',543,4.6,'nigerian literature,biafra,civil war,historical fiction,novel',NOW(),NOW()),
('978-0141186101','Petals of Blood','Ngugi wa Thiong''o','Penguin Classics',2005,'African Literature','Four suspects in a murder investigation recount post independence Kenya, exposing the betrayals of a new political and economic elite.',3,3,1,'English',432,4.3,'kenyan literature,postcolonial,politics,novel,fiction',NOW(),NOW()),
('978-0435905102','The Joys of Motherhood','Buchi Emecheta','Heinemann',2008,'African Literature','A woman in colonial Lagos measures her worth by motherhood, and finds the traditional bargain broken by a changing urban Nigeria.',3,3,1,'English',224,4.2,'nigerian literature,women,motherhood,lagos,novel',NOW(),NOW()),
('978-0141439103','Pride and Prejudice','Jane Austen','Penguin Classics',2003,'World Literature','Elizabeth Bennet navigates family pressure, social class and her own first impressions in this comedy of manners set in Regency England.',4,4,1,'English',480,4.5,'classic,romance,novel,english literature,fiction',NOW(),NOW()),
('978-0451524104','Nineteen Eighty-Four','George Orwell','Signet Classics',1961,'World Literature','In a state of permanent surveillance and rewritten history, one man tries to hold on to private thought and independent memory.',4,4,1,'English',328,4.6,'dystopia,classic,politics,surveillance,novel',NOW(),NOW()),
('978-0060883105','One Hundred Years of Solitude','Gabriel Garcia Marquez','Harper Perennial',2006,'World Literature','The rise and fall of the Buendia family across seven generations in the mythical town of Macondo, told in the language of magical realism.',3,3,1,'English',417,4.4,'magical realism,latin american literature,classic,novel',NOW(),NOW()),
('978-0140424106','Collected Poems','Wole Soyinka','Methuen Drama',2007,'Poetry and Drama','Poems spanning decades from the Nobel laureate, ranging across prison writing, Yoruba mythology, politics and personal elegy.',2,2,1,'English',256,4.3,'poetry,nigerian literature,soyinka,verse,drama',NOW(),NOW()),
('978-0743477107','Hamlet','William Shakespeare','Simon and Schuster',2003,'Poetry and Drama','A prince is asked by his father''s ghost to avenge a murder, and hesitates through grief, doubt and the problem of knowing what is true.',4,4,1,'English',342,4.5,'shakespeare,drama,tragedy,play,classic',NOW(),NOW()),
('978-0435272108','The Lion and the Jewel','Wole Soyinka','Oxford University Press',1963,'Poetry and Drama','A village schoolteacher and an ageing chief compete for the same young woman, in a comedy about tradition, modernity and vanity.',3,3,1,'English',64,4.1,'drama,play,nigerian literature,comedy,tradition',NOW(),NOW()),
('978-0441013109','Dune','Frank Herbert','Ace Books',2005,'Science Fiction','On a desert planet holding the most valuable substance in the universe, a young heir is drawn into prophecy, ecology and interstellar politics.',3,3,1,'English',688,4.5,'science fiction,space,politics,ecology,novel',NOW(),NOW()),
('978-0553380110','Foundation','Isaac Asimov','Bantam Spectra',2004,'Science Fiction','A mathematician predicts the collapse of a galactic empire and founds a colony intended to shorten the coming dark age.',3,3,1,'English',244,4.3,'science fiction,space,empire,future,novel',NOW(),NOW()),
('978-0307474111','The Girl with the Dragon Tattoo','Stieg Larsson','Vintage Crime',2009,'Crime and Thriller','A disgraced journalist and a brilliant antisocial hacker investigate a disappearance that has gone unsolved for forty years.',3,3,1,'English',672,4.2,'crime,thriller,mystery,detective,novel',NOW(),NOW()),
('978-0062073112','Murder on the Orient Express','Agatha Christie','William Morrow',2011,'Crime and Thriller','Hercule Poirot is trapped on a snowbound train with a corpse, a dozen suspects and a solution that nobody expects.',3,3,1,'English',274,4.4,'crime,mystery,detective,classic,novel',NOW(),NOW()),
('978-0747532113','Harry Potter and the Philosopher''s Stone','J. K. Rowling','Bloomsbury',2014,'Children''s Literature','An orphaned boy discovers on his eleventh birthday that he is a wizard, and begins his first year at a school of magic.',5,5,1,'English',352,4.7,'children,fantasy,magic,school,novel',NOW(),NOW()),
('978-0064471114','The Lion, the Witch and the Wardrobe','C. S. Lewis','HarperCollins',2005,'Children''s Literature','Four children step through a wardrobe into a land held in endless winter, and join a talking lion in the fight to free it.',4,4,1,'English',208,4.5,'children,fantasy,adventure,narnia,novel',NOW(),NOW()),

-- Arts, Media and Lifestyle -------------------------------------------------------
('978-0714832115','The Story of Art','Ernst Gombrich','Phaidon Press',2006,'Art and Design','A narrative history of art from cave painting to modernism, explaining how styles developed and what artists were trying to solve.',3,3,1,'English',688,4.6,'art history,painting,sculpture,design,culture',NOW(),NOW()),
('978-0321934116','The Non-Designer''s Design Book','Robin Williams','Peachpit Press',2014,'Art and Design','Four practical principles that make layouts look professional: contrast, repetition, alignment and proximity, applied to real documents.',3,3,1,'English',240,4.4,'graphic design,layout,typography,visual design',NOW(),NOW()),
('978-0393975117','The Study of Orchestration','Samuel Adler','W. W. Norton',2016,'Music','How instruments combine: the ranges and colours of orchestral instruments, scoring for sections, and balancing texture across the ensemble.',2,2,1,'English',832,4.3,'music,orchestration,composition,instruments,theory',NOW(),NOW()),
('978-0876390118','Music Theory for Beginners','Michael Pilhofer','For Dummies',2019,'Music','Reading and understanding written music: notes and rhythm, scales and key signatures, intervals, chords and basic harmony.',3,3,1,'English',288,4.1,'music theory,notation,scales,chords,beginner',NOW(),NOW()),
('978-1492571119','Anatomy of Strength Training','Frederic Delavier','Human Kinetics',2018,'Sports and Fitness','Illustrated guide to resistance exercises, showing which muscles each movement works and how to perform them without injury.',3,3,1,'English',192,4.5,'fitness,strength training,exercise,muscles,gym',NOW(),NOW()),
('978-1718201120','The Science of Running','Steve Magness','Origin Press',2014,'Sports and Fitness','The physiology behind endurance performance and how to structure training: aerobic development, lactate threshold, periodisation and recovery.',2,2,1,'English',300,4.3,'running,endurance,training,sports science,fitness',NOW(),NOW()),
('978-0307958121','Salt, Fat, Acid, Heat','Samin Nosrat','Simon and Schuster',2017,'Cooking','The four elements that determine whether food tastes good, taught as principles rather than recipes so any dish can be improved.',3,3,1,'English',480,4.7,'cooking,food,recipes,technique,kitchen',NOW(),NOW()),
('978-1607747122','The Food Lab','J. Kenji Lopez-Alt','W. W. Norton',2015,'Cooking','Kitchen science applied to everyday cooking, testing common techniques to find out what actually works and why.',2,2,1,'English',958,4.6,'cooking,food science,recipes,technique,kitchen',NOW(),NOW()),
('978-1786570123','Lonely Planet West Africa','Lonely Planet','Lonely Planet',2022,'Travel','A practical guide to travelling in West Africa: routes and transport, where to stay, local customs, safety advice and regional highlights.',2,2,1,'English',560,4.0,'travel,west africa,guide,tourism,culture',NOW(),NOW()),
('978-0143107124','The Art of Travel','Alain de Botton','Penguin Books',2004,'Travel','A reflective look at why we travel and what we hope to find, drawing on writers and painters who wrestled with the same question.',2,2,1,'English',272,4.1,'travel,philosophy,essays,journeys,reflection',NOW(),NOW()),
('978-0132492125','News Reporting and Writing','Melvin Mencher','McGraw-Hill',2019,'Journalism','The craft of reporting: finding and verifying stories, interviewing, structuring news copy, covering beats and applying journalistic ethics.',3,3,1,'English',608,4.1,'journalism,reporting,writing,media,ethics',NOW(),NOW()),
('978-0745671126','Media and Society','Graeme Burton','Bloomsbury Academic',2020,'Journalism','How mass media shapes public understanding: ownership and regulation, representation, audiences, advertising and the rise of digital platforms.',2,2,1,'English',400,4.0,'media studies,communication,society,advertising,digital',NOW(),NOW())
-- The legacy VALUES(col) form is used deliberately instead of the newer
-- "AS new" row alias: the alias syntax needs MySQL 8.0.19+ and is not supported
-- by MariaDB, which is what XAMPP ships on Windows.
ON DUPLICATE KEY UPDATE
    title             = VALUES(title),
    author            = VALUES(author),
    publisher         = VALUES(publisher),
    publication_year  = VALUES(publication_year),
    category          = VALUES(category),
    description       = VALUES(description),
    total_copies      = VALUES(total_copies),
    available_copies  = VALUES(available_copies),
    is_active         = VALUES(is_active),
    language          = VALUES(language),
    pages             = VALUES(pages),
    rating            = VALUES(rating),
    tags              = VALUES(tags),
    updated_at        = NOW();

-- Confirm what landed.
SELECT COUNT(*) AS active_books FROM books WHERE is_active = 1;
SELECT category, COUNT(*) AS books FROM books WHERE is_active = 1 GROUP BY category ORDER BY category;
